name: Create release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+-?**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: build with maven
        run: ./mvnw -Drevision=${{github.ref_name}} -Dchangelist="" -Drelease.url="https://github.com/SCDH/oxbytao/releases/download/${{ github.ref_name }}/" --batch-mode --update-snapshots verify

      - name: store oxygen framework descriptor file
        uses: actions/upload-artifact@v4
        with:
          name: oxygen-framework-descriptor
          path: target/descriptor.xml
          retention-days: 1

      - name: create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body_path: changeLog.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload framework package to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/oxbytao-${{ github.ref_name }}-package.zip
          asset_name: oxbytao-${{ github.ref_name }}-package.zip
          asset_content_type: application/zip

  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: Download descriptor artifact
        uses: actions/download-artifact@v4
        with:
          name: oxygen-framework-descriptor

      - name: create directory for github pages
        run: mkdir -p public

      - name: copy descriptor file
        run: cp target/descriptor.xml public/

      - name: Deploy descriptor file on Github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
